name: Static checks
on:
  pull_request:
jobs:
  types_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install node dependencies
        run: yarn
      - name: Check formatting
        run: yarn format:check
      - name: Check types
        run: yarn typecheck
      - name: Check build
        run: yarn build
